name: 自动收割指挥中心

on:
  schedule:
    - cron: '0 */4 * * *'  # 每 4 小时全自动收割一次
  workflow_dispatch:      # 开启手动触发开关（遥控器）
    inputs:
      search_key:
        description: '请输入搜索关键词'
        required: true
        default: 'fastervpn.world "hysteria2"'
      custom_url:
        description: '输入临时 Raw 源链接'
        required: false
        default: ''

jobs:
  harvest_job:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置 Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: 安装依赖
        run: pip install requests

      - name: 执行收割
        env:
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          # 把界面输入的东西传给 Python
          INPUT_SEARCH_KEY: ${{ github.event.inputs.search_key }}
          INPUT_CUSTOM_URL: ${{ github.event.inputs.custom_url }}
        run: python main.py

      - name: 提交更新
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add proxies.yaml
          git commit -m "Auto-update: $(date +'%Y-%m-%d %H:%M')" || exit 0
          git push
